#https://docs.docker.com/compose/compose-file/
version: '3'
services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: pypy3-sodapy
    #env_file: .env
    #command: 
    volumes:
      - .:/app
    working_dir: /app
