#https://docs.docker.com/compose/compose-file/
version: '3'
services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: pypy3-sodapy
#    env_file: .env
#    command: 
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    image: nginx:latest
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
